# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-24 10:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0002_contactdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='location',
            new_name='locations',
        ),
        migrations.RenameField(
            model_name='contactdata',
            old_name='shift',
            new_name='shifts',
        ),
    ]
