# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-24 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instituteapp', '0003_auto_20190524_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactdata',
            old_name='emai',
            new_name='email',
        ),
    ]
